-- Baseline schema. Portable SQL: runs on PostgreSQL and on H2 in PostgreSQL mode.

CREATE TABLE app_users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    CONSTRAINT uq_app_users_username UNIQUE (username)
);

CREATE TABLE lanes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50) NOT NULL,
    terminal   VARCHAR(10) NOT NULL,
    status     VARCHAR(20) NOT NULL,
    updated_at TIMESTAMP   NOT NULL
);

CREATE TABLE inspections (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lane_id      BIGINT      NOT NULL,
    equipment    VARCHAR(40) NOT NULL,
    result       VARCHAR(10) NOT NULL,
    notes        VARCHAR(500),
    inspected_by VARCHAR(50) NOT NULL,
    created_at   TIMESTAMP   NOT NULL,
    CONSTRAINT fk_inspections_lane FOREIGN KEY (lane_id) REFERENCES lanes (id)
);

CREATE INDEX idx_inspections_lane_id ON inspections (lane_id);
CREATE INDEX idx_inspections_result ON inspections (result);
CREATE INDEX idx_inspections_created_at ON inspections (created_at);
